FROM node:20-alpine AS builder
ARG API_URL=https://api.clubpro.com.ar
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN sed -i "s|http://localhost:8000|${API_URL}|g" src/environments/environment.prod.ts \
    && npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist/padel-center-admin/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
